# Generated by Django 3.2.6 on 2021-11-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_app', '0002_auto_20211104_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
